# Generated by Django 4.2.7 on 2025-11-03 14:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='platform_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('MTN_MOMO', 'MTN Mobile Money'), ('CASH', 'Espèces'), ('BANK_TRANSFER', 'Virement bancaire')], default='MOBILE_MONEY', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PAYMENT', 'Paiement'), ('REFUND', 'Remboursement'), ('COMMISSION', 'Commission'), ('PAYOUT', 'Paiement agriculteur')], default='PAYMENT', max_length=20),
        ),
    ]
