# Generated by Django 4.2.9 on 2025-11-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('categorie_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('produit_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('est_bio', models.BooleanField(default=False)),
                ('est_publier', models.BooleanField(default=False)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('condition_conservation', models.TextField(blank=True, null=True)),
                ('id_agriculteur', models.IntegerField()),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='product_app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_fichier', models.URLField()),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='product_app.produit')),
            ],
        ),
    ]
