# Generated by Django 3.2.9 on 2025-10-24 09:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('token', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_schema_blacklist_tokens',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('user_id', models.UUIDField()),
                ('expiration', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_schema_refresh_tokens',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('acheteur', 'Acheteur'), ('vendeur', 'Vendeur'), ('admin', 'Administrateur')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_schema_users',
            },
        ),
    ]
