# Generated by Django 5.2.7 on 2025-10-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_auto_20251024_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklisttoken',
            options={'verbose_name': 'Token blacklisté', 'verbose_name_plural': 'Tokens blacklistés'},
        ),
        migrations.AlterModelOptions(
            name='refreshtoken',
            options={'verbose_name': 'Token de rafraîchissement', 'verbose_name_plural': 'Tokens de rafraîchissement'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='user_id',
        ),
        migrations.AddField(
            model_name='refreshtoken',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='auth_app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
